name: ci

on:
  pull_request:

jobs:
  build_image:
    runs-on: ubuntu-latest
    env:
      PLATFORMS: linux/amd64,linux/arm64/v8
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            Dockerfile
            requirements.txt

      - name: Get deluge version
        id: deluge_version
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          VERSION=$(python -c "from pkg_resources import parse_requirements; print(next(filter(lambda r: r.name == 'deluge', parse_requirements(open('requirements.txt').read()))).specs[0][1])")
          echo $VERSION
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ env.PLATFORMS }}

      - name: Set up Docker Buildx
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ env.PLATFORMS }}

      - name: Build
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: docker/build-push-action@v4
        with:
          push: false
          build-args: |
            VERSION=${{ steps.deluge_version.outputs.version }}
          platforms: ${{ env.PLATFORMS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
