name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deluge_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.deluge_version.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Get deluge version
        id: deluge_version
        run: |
          pip install -q pkginfo
          pip wheel --no-deps -r requirements.txt
          VERSION=$(pkginfo *.whl -f version --single)
          echo $VERSION
          echo "::set-output name=version::${VERSION}"
  docker:
    runs-on: ubuntu-latest
    needs: deluge_version
    env:
      PLATFORMS: linux/amd64,linux/arm64/v8,linux/arm/v7
      DOCKERHUB_USERNAME: isac322
    steps:
      - uses: actions/checkout@v2
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v3.6.0
        with:
          flavor: latest=true
          images: ${{ env.DOCKERHUB_USERNAME }}/deluged
          tags: |
            type=raw,value=${{ needs.deluge_version.outputs.version }}
          labels: |
            maintainer=${{ env.DOCKERHUB_USERNAME }}
            org.opencontainers.image.title=deluged
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: ${{ env.PLATFORMS }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.DOCKERHUB_USERNAME }}/deluged:latest
          cache-to: type=inline
      - name: Update repo description
        if: github.event_name != 'pull_request'
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.DOCKERHUB_USERNAME }}/deluged
