---
name: Release and Publish

on:
  push:
    branches:
      - master
    paths:
      - Dockerfile
      - requirements.txt
      - .github/workflows/release-and-publish.yaml
  workflow_dispatch:

concurrency: # Run release builds sequentially, cancel outdated PR builds
  group: ci-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

permissions: # Grant write access to github.token within non-pull_request builds
  contents: write

jobs:
  build_image:
    runs-on: ubuntu-latest
    env:
      PLATFORMS: linux/amd64,linux/arm64/v8
      DOCKERHUB_USERNAME: isac322
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - id: release
        name: Prepare release
        uses: mgoltzsche/conventional-release@v0

      - name: Docker meta
        if: steps.release.outputs.publish # To run only when release build
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          flavor: latest=true
          images: ${{ env.DOCKERHUB_USERNAME }}/deluged
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          labels: |
            maintainer=${{ env.DOCKERHUB_USERNAME }}
            org.opencontainers.image.title=deluged
            org.opencontainers.image.source=https://git.deluge-torrent.org/deluge
            org.opencontainers.image.documentation=https://deluge-torrent.org/
      - name: Set up QEMU
        if: steps.release.outputs.publish # To run only when release build
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ env.PLATFORMS }}
      - name: Set up Docker Buildx
        if: steps.release.outputs.publish # To run only when release build
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ env.PLATFORMS }}
      - name: Login to Docker Hub
        if: steps.release.outputs.publish # To run only when release build
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        if: steps.release.outputs.publish # To run only when release build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: |
            VERSION=${{ steps.docker_meta.outputs.version }}
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
